/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestDbRouteImport } from './routes/test-db'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkerDashboardRouteImport } from './routes/worker/dashboard'
import { Route as StudentPortalRouteImport } from './routes/student/portal'
import { Route as DirectorDashboardRouteImport } from './routes/director/dashboard'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/student'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedStudentIndexRouteImport } from './routes/_authenticated/student/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicBootstrapRouteImport } from './routes/api/public/bootstrap'
import { Route as AuthenticatedStudentNotificationsRouteImport } from './routes/_authenticated/student/notifications'
import { Route as AuthenticatedStudentMenuRouteImport } from './routes/_authenticated/student/menu'
import { Route as AuthenticatedAdminValidationRouteImport } from './routes/_authenticated/admin/validation'
import { Route as AuthenticatedAdminUniversitiesRouteImport } from './routes/_authenticated/admin/universities'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin/students'
import { Route as AuthenticatedAdminPasswordsRouteImport } from './routes/_authenticated/admin/passwords'
import { Route as AuthenticatedAdminInviteRouteImport } from './routes/_authenticated/admin/invite'
import { Route as AuthenticatedAdminBrandingRouteImport } from './routes/_authenticated/admin/branding'
import { Route as AuthenticatedStudentStepStepRouteImport } from './routes/_authenticated/student/step.$step'

const TestDbRoute = TestDbRouteImport.update({
  id: '/test-db',
  path: '/test-db',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerDashboardRoute = WorkerDashboardRouteImport.update({
  id: '/worker/dashboard',
  path: '/worker/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentPortalRoute = StudentPortalRouteImport.update({
  id: '/student/portal',
  path: '/student/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorDashboardRoute = DirectorDashboardRouteImport.update({
  id: '/director/dashboard',
  path: '/director/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicBootstrapRoute = ApiPublicBootstrapRouteImport.update({
  id: '/api/public/bootstrap',
  path: '/api/public/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentNotificationsRoute =
  AuthenticatedStudentNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentMenuRoute =
  AuthenticatedStudentMenuRouteImport.update({
    id: '/menu',
    path: '/menu',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedAdminValidationRoute =
  AuthenticatedAdminValidationRouteImport.update({
    id: '/validation',
    path: '/validation',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUniversitiesRoute =
  AuthenticatedAdminUniversitiesRouteImport.update({
    id: '/universities',
    path: '/universities',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPasswordsRoute =
  AuthenticatedAdminPasswordsRouteImport.update({
    id: '/passwords',
    path: '/passwords',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInviteRoute =
  AuthenticatedAdminInviteRouteImport.update({
    id: '/invite',
    path: '/invite',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBrandingRoute =
  AuthenticatedAdminBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedStudentStepStepRoute =
  AuthenticatedStudentStepStepRouteImport.update({
    id: '/step/$step',
    path: '/step/$step',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/test-db': typeof TestDbRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/student': typeof AuthenticatedStudentRouteWithChildren
  '/director/dashboard': typeof DirectorDashboardRoute
  '/student/portal': typeof StudentPortalRoute
  '/worker/dashboard': typeof WorkerDashboardRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/invite': typeof AuthenticatedAdminInviteRoute
  '/admin/passwords': typeof AuthenticatedAdminPasswordsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/universities': typeof AuthenticatedAdminUniversitiesRoute
  '/admin/validation': typeof AuthenticatedAdminValidationRoute
  '/student/menu': typeof AuthenticatedStudentMenuRoute
  '/student/notifications': typeof AuthenticatedStudentNotificationsRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/student/': typeof AuthenticatedStudentIndexRoute
  '/student/step/$step': typeof AuthenticatedStudentStepStepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/test-db': typeof TestDbRoute
  '/director/dashboard': typeof DirectorDashboardRoute
  '/student/portal': typeof StudentPortalRoute
  '/worker/dashboard': typeof WorkerDashboardRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/invite': typeof AuthenticatedAdminInviteRoute
  '/admin/passwords': typeof AuthenticatedAdminPasswordsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/universities': typeof AuthenticatedAdminUniversitiesRoute
  '/admin/validation': typeof AuthenticatedAdminValidationRoute
  '/student/menu': typeof AuthenticatedStudentMenuRoute
  '/student/notifications': typeof AuthenticatedStudentNotificationsRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/student': typeof AuthenticatedStudentIndexRoute
  '/student/step/$step': typeof AuthenticatedStudentStepStepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/test-db': typeof TestDbRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/student': typeof AuthenticatedStudentRouteWithChildren
  '/director/dashboard': typeof DirectorDashboardRoute
  '/student/portal': typeof StudentPortalRoute
  '/worker/dashboard': typeof WorkerDashboardRoute
  '/_authenticated/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/_authenticated/admin/invite': typeof AuthenticatedAdminInviteRoute
  '/_authenticated/admin/passwords': typeof AuthenticatedAdminPasswordsRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/admin/universities': typeof AuthenticatedAdminUniversitiesRoute
  '/_authenticated/admin/validation': typeof AuthenticatedAdminValidationRoute
  '/_authenticated/student/menu': typeof AuthenticatedStudentMenuRoute
  '/_authenticated/student/notifications': typeof AuthenticatedStudentNotificationsRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexRoute
  '/_authenticated/student/step/$step': typeof AuthenticatedStudentStepStepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/test-db'
    | '/admin'
    | '/student'
    | '/director/dashboard'
    | '/student/portal'
    | '/worker/dashboard'
    | '/admin/branding'
    | '/admin/invite'
    | '/admin/passwords'
    | '/admin/students'
    | '/admin/universities'
    | '/admin/validation'
    | '/student/menu'
    | '/student/notifications'
    | '/api/public/bootstrap'
    | '/admin/'
    | '/student/'
    | '/student/step/$step'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/test-db'
    | '/director/dashboard'
    | '/student/portal'
    | '/worker/dashboard'
    | '/admin/branding'
    | '/admin/invite'
    | '/admin/passwords'
    | '/admin/students'
    | '/admin/universities'
    | '/admin/validation'
    | '/student/menu'
    | '/student/notifications'
    | '/api/public/bootstrap'
    | '/admin'
    | '/student'
    | '/student/step/$step'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/test-db'
    | '/_authenticated/admin'
    | '/_authenticated/student'
    | '/director/dashboard'
    | '/student/portal'
    | '/worker/dashboard'
    | '/_authenticated/admin/branding'
    | '/_authenticated/admin/invite'
    | '/_authenticated/admin/passwords'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/universities'
    | '/_authenticated/admin/validation'
    | '/_authenticated/student/menu'
    | '/_authenticated/student/notifications'
    | '/api/public/bootstrap'
    | '/_authenticated/admin/'
    | '/_authenticated/student/'
    | '/_authenticated/student/step/$step'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  TestDbRoute: typeof TestDbRoute
  DirectorDashboardRoute: typeof DirectorDashboardRoute
  StudentPortalRoute: typeof StudentPortalRoute
  WorkerDashboardRoute: typeof WorkerDashboardRoute
  ApiPublicBootstrapRoute: typeof ApiPublicBootstrapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-db': {
      id: '/test-db'
      path: '/test-db'
      fullPath: '/test-db'
      preLoaderRoute: typeof TestDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/dashboard': {
      id: '/worker/dashboard'
      path: '/worker/dashboard'
      fullPath: '/worker/dashboard'
      preLoaderRoute: typeof WorkerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/portal': {
      id: '/student/portal'
      path: '/student/portal'
      fullPath: '/student/portal'
      preLoaderRoute: typeof StudentPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/director/dashboard': {
      id: '/director/dashboard'
      path: '/director/dashboard'
      fullPath: '/director/dashboard'
      preLoaderRoute: typeof DirectorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/bootstrap': {
      id: '/api/public/bootstrap'
      path: '/api/public/bootstrap'
      fullPath: '/api/public/bootstrap'
      preLoaderRoute: typeof ApiPublicBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/student/notifications': {
      id: '/_authenticated/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof AuthenticatedStudentNotificationsRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/menu': {
      id: '/_authenticated/student/menu'
      path: '/menu'
      fullPath: '/student/menu'
      preLoaderRoute: typeof AuthenticatedStudentMenuRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/admin/validation': {
      id: '/_authenticated/admin/validation'
      path: '/validation'
      fullPath: '/admin/validation'
      preLoaderRoute: typeof AuthenticatedAdminValidationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/universities': {
      id: '/_authenticated/admin/universities'
      path: '/universities'
      fullPath: '/admin/universities'
      preLoaderRoute: typeof AuthenticatedAdminUniversitiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/passwords': {
      id: '/_authenticated/admin/passwords'
      path: '/passwords'
      fullPath: '/admin/passwords'
      preLoaderRoute: typeof AuthenticatedAdminPasswordsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invite': {
      id: '/_authenticated/admin/invite'
      path: '/invite'
      fullPath: '/admin/invite'
      preLoaderRoute: typeof AuthenticatedAdminInviteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/branding': {
      id: '/_authenticated/admin/branding'
      path: '/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AuthenticatedAdminBrandingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/student/step/$step': {
      id: '/_authenticated/student/step/$step'
      path: '/step/$step'
      fullPath: '/student/step/$step'
      preLoaderRoute: typeof AuthenticatedStudentStepStepRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBrandingRoute: typeof AuthenticatedAdminBrandingRoute
  AuthenticatedAdminInviteRoute: typeof AuthenticatedAdminInviteRoute
  AuthenticatedAdminPasswordsRoute: typeof AuthenticatedAdminPasswordsRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminUniversitiesRoute: typeof AuthenticatedAdminUniversitiesRoute
  AuthenticatedAdminValidationRoute: typeof AuthenticatedAdminValidationRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBrandingRoute: AuthenticatedAdminBrandingRoute,
  AuthenticatedAdminInviteRoute: AuthenticatedAdminInviteRoute,
  AuthenticatedAdminPasswordsRoute: AuthenticatedAdminPasswordsRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAdminUniversitiesRoute: AuthenticatedAdminUniversitiesRoute,
  AuthenticatedAdminValidationRoute: AuthenticatedAdminValidationRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedStudentRouteChildren {
  AuthenticatedStudentMenuRoute: typeof AuthenticatedStudentMenuRoute
  AuthenticatedStudentNotificationsRoute: typeof AuthenticatedStudentNotificationsRoute
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
  AuthenticatedStudentStepStepRoute: typeof AuthenticatedStudentStepStepRoute
}

const AuthenticatedStudentRouteChildren: AuthenticatedStudentRouteChildren = {
  AuthenticatedStudentMenuRoute: AuthenticatedStudentMenuRoute,
  AuthenticatedStudentNotificationsRoute:
    AuthenticatedStudentNotificationsRoute,
  AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
  AuthenticatedStudentStepStepRoute: AuthenticatedStudentStepStepRoute,
}

const AuthenticatedStudentRouteWithChildren =
  AuthenticatedStudentRoute._addFileChildren(AuthenticatedStudentRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedStudentRoute: AuthenticatedStudentRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  TestDbRoute: TestDbRoute,
  DirectorDashboardRoute: DirectorDashboardRoute,
  StudentPortalRoute: StudentPortalRoute,
  WorkerDashboardRoute: WorkerDashboardRoute,
  ApiPublicBootstrapRoute: ApiPublicBootstrapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
